# Análise E-Comerce Brasil Olist

Dados de transações comerciais entre 2016 e 2018.
Dados anonimizados utilizando hash.

## Principais pontos

    
**Análises de Vendas e Performance**

    Qual o faturamento total e evolução temporal das vendas?
    Quais os meses/períodos com maior volume de vendas?
    Qual o ticket médio dos pedidos?
    Qual a taxa de crescimento das vendas ao longo do período?
    Qual a distribuição de vendas por categoria de produto?

**Análises de Satisfação**

    Qual a nota média de satisfação dos clientes?
    Quais fatores mais impactam a avaliação (prazo, produto, atendimento)?
    Quais produtos estão mais propensos a avaliações negativas?
    Qual a distribuição das notas (1-5 estrelas)?
    Existe correlação entre atraso na entrega e avaliações negativas?

**Análises de Pagamento**

    Quais as formas de pagamento mais utilizadas?
    Qual o valor médio por tipo de pagamento?
    Existe relação entre método de pagamento e ticket médio?

**Análises de Logística e Entrega**

    Qual o prazo médio de entrega?
    Percentual de entregas no prazo vs atrasadas?

**Análises de Produtos**

    Quais categorias de produtos mais vendidas?
    Produtos com melhores avaliações?

**Análises de Vendedores**

    Quantidade e performance dos vendedores?
    Concentração de vendas (poucos vendem muito)?
    Relação entre localização do vendedor e performance?

**Análises Preditivas e ML**

    Previsão de demanda por categoria/período
    Predição de satisfação do cliente
    Classificação de risco de review negativa
    Previsão de churn de clientes
    Sistemas de recomendação

Entendimento do negócio:

Empresa no ramo de e-commerce atua na modalidade B2B2BC conectando logistas a clientes. Tem como principal característica a centralização dos pedidos, logo, seu público alvo são os vendedores parceiros.

A empresa agrega os pedidos de diferentes plataformas(Mercado Livre, Americanas, Magazine Luiza entre outras) em uma só plataforma, onde cada vendedor tem um painel único, com os pedidos que devem ser embalados e despachados.


Objetivo de Negócio:

Melhorar o desempenho comercial e a satisfação do cliente, orientando decisões baseadas em dados.

Tais perguntas devem ser respondidas:
Como anda as vendas;
Quais estados vendem mais;
Onde está a maior concentração de seus clientes;
Quais fatores mais impactam nas avaliações negativas;
Quais categorias de produtos vendem melhor;
Produtos com maior taxa de avaliações negativas entre outras.


Objetivo de Mineração de Dados:

Realizar uma análise exploratória e preditiva sobre:

 Vendas;
Localização dos clientes;
Categorias de produtos;
Fatores que influenciam as avaliações.


Será considerado um sucesso se as seguintes características forem atendidas:

Aumentar em 5% a captação de novos usuários(Tendo em vista ações de marketing melhor direcionadas)
Melhorar a avaliação média dos pedidos em, no mínimo, 0,2 pontos


Responsáveis e cronograma

A análise será conduzida por Guilherme da Silva Costa, com orientação do Prof Bruno Martins Bartolomeu.

Espera-se que a análise seja concluída até o fim de novembro(29/11/2025). Será utilizado a linguagem python e suas bibliotecas.

## Importação

In [2]:
import pandas as pd

# Origem https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce


costumer = pd.read_csv('olist_customers_dataset.csv')
local = pd.read_csv('olist_geolocation_dataset.csv')
order_items = pd.read_csv('olist_order_items_dataset.csv')
order_payments = pd.read_csv('olist_order_payments_dataset.csv')
order_reviews = pd.read_csv('olist_order_reviews_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
sellers = pd.read_csv('olist_sellers_dataset.csv')
category_name_translation = pd.read_csv('product_category_name_translation.csv')

In [ ]:
df = orders.merge(order_items, how='left', on='order_id')
df.shape

(113425, 14)

In [56]:
def visualiza_df(df):
    '''
        Exibe informações básicas do DataFrame que está sendo observado 
    '''
    #Formato do DF
    print('\033[31m Formato:\033[0m')
    print(f'{df.shape[0] :,} linhas e {df.shape[1]} colunas.')
    # Valores ausentes
    print(f'{'=' * 50}')
    print('\033[31m Valores ausentes:\033[0m')
    print(df.isnull().sum())

    # Duplicatas
    print(f'{'=' * 50}')
    print('\033[31m Duplicatas: \033[0m')
    print(df.duplicated().sum())

    # Tipos de dados
    print(f'{'=' * 50}')
    print('\033[31m Tipos de dados: \033[0m')
    print(df.dtypes)

    # Visualização dados brutos
    print(f'{'=' * 50}')
    print('\033[31m Pré-visualização dos dados: \033[0m')
    df.head(5)

    return df

In [67]:
visualiza_df(orders)
orders['order_status'].value_counts()

 Formato:
99,441 linhas e 8 colunas.
==================================================
 Valores ausentes:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object
==================================================
 Pré-visualização dos dados:

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [63]:
order_payments['payment_installments'].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [ ]:
df = df.merge(sellers,  how='left', on='seller_id')
df.shape

(113425, 17)

In [ ]:
df = df.merge(costumer, how='left', on='customer_id')
df.shape

(113425, 21)

In [ ]:
df = df.merge(products, how='left', on='product_id')
df.shape

(113425, 29)

In [ ]:
df = df.merge(category_name_translation, how='left', on='product_category_name')
df.shape

(113425, 30)

##

In [ ]:
df.describe()

,order_item_id,price,freight_value,seller_zip_code_prefix,customer_zip_code_prefix,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,112650.000000,112650.000000,112650.000000,112650.000000,113425.000000,111047.000000,111047.000000,111047.000000,112632.000000,112632.000000,112632.000000,112632.000000
mean,1.197834,120.653739,19.990320,24439.170431,35102.472965,48.775978,787.867029,2.209713,2093.672047,30.153669,16.593766,22.996546
std,0.705124,183.633928,15.806405,27596.030909,29864.919733,10.025581,652.135608,1.721438,3751.596884,16.153449,13.443483,11.707268
min,1.000000,0.850000,0.000000,1001.000000,1003.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,1.000000,39.900000,13.080000,6429.000000,11250.000000,42.000000,348.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,1.000000,74.990000,16.260000,13568.000000,24320.000000,52.000000,603.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,1.000000,134.900000,21.150000,27930.000000,59020.000000,57.000000,987.000000,3.000000,1800.000000,38.000000,20.000000,30.000000
max,21.000000,6735.000000,409.680000,99730.000000,99990.000000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  object
 1   customer_id                    113425 non-null  object
 2   order_status                   113425 non-null  object
 3   order_purchase_timestamp       113425 non-null  object
 4   order_approved_at              113264 non-null  object
 5   order_delivered_carrier_date   111457 non-null  object
 6   order_delivered_customer_date  110196 non-null  object
 7   order_estimated_delivery_date  113425 non-null  object
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  object
 10  seller_id                      112650 non-null  object
 11  shipping_limit_date            112650 non-null  object
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
 14  seller_zip_code_prefix         112650 non-null  float64
 15  seller_city                    112650 non-null  object
 16  seller_state                   112650 non-null  object
 17  customer_unique_id             113425 non-null  object
 18  customer_zip_code_prefix       113425 non-null  int64
 19  customer_city                  113425 non-null  object
 20  customer_state                 113425 non-null  object
 21  product_category_name          111047 non-null  object
 22  product_name_lenght            111047 non-null  float64
 23  product_description_lenght     111047 non-null  float64
 24  product_photos_qty             111047 non-null  float64
 25  product_weight_g               112632 non-null  float64
 26  product_length_cm              112632 non-null  float64
 27  product_height_cm              112632 non-null  float64
 28  product_width_cm               112632 non-null  float64
 29  product_category_name_english  111023 non-null  object
dtypes: float64(11), int64(1), object(18)
memory usage: 26.0+ MB

In [ ]:
df.select_dtypes(include=['number']).corr()

,order_item_id,price,freight_value,seller_zip_code_prefix,customer_zip_code_prefix,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
order_item_id,1.000000,-0.060522,-0.029380,-0.018721,-0.000874,-0.022662,-0.014311,-0.055852,-0.003549,0.005628,0.029323,-0.010732
price,-0.060522,1.000000,0.414204,0.086416,0.042467,0.017001,0.198166,0.051848,0.338819,0.145811,0.223602,0.172467
freight_value,-0.029380,0.414204,1.000000,0.150204,0.225690,0.023611,0.093855,0.022259,0.610420,0.309086,0.391831,0.323777
seller_zip_code_prefix,-0.018721,0.086416,0.150204,1.000000,0.076078,-0.031412,0.059581,-0.045357,0.009709,0.033426,0.012570,-0.016362
customer_zip_code_prefix,-0.000874,0.042467,0.225690,0.076078,1.000000,0.015515,0.023709,0.019626,0.003242,0.007491,0.011746,-0.008723
product_name_lenght,-0.022662,0.017001,0.023611,-0.031412,0.015515,1.000000,0.091524,0.145904,0.022731,0.060447,-0.028170,0.064442
product_description_lenght,-0.014311,0.198166,0.093855,0.059581,0.023709,0.091524,1.000000,0.118087,0.059710,0.005971,0.072724,-0.068419
product_photos_qty,-0.055852,0.051848,0.022259,-0.045357,0.019626,0.145904,0.118087,1.000000,0.022667,0.047503,-0.033399,0.010367
product_weight_g,-0.003549,0.338819,0.610420,0.009709,0.003242,0.022731,0.059710,0.022667,1.000000,0.460919,0.583277,0.506609
product_length_cm,0.005628,0.145811,0.309086,0.033426,0.007491,0.060447,0.005971,0.047503,0.460919,1.000000,0.192895,0.532537
product_height_cm,0.029323,0.223602,0.391831,0.012570,0.011746,-0.028170,0.072724,-0.033399,0.583277,0.192895,1.000000,0.281224
product_width_cm,-0.010732,0.172467,0.323777,-0.016362,-0.008723,0.064442,-0.068419,0.010367,0.506609,0.532537,0.281224,1.000000