# Análise E-Comerce Brasil Olist

Dados de transações comerciais entre 2016 e 2018.
Dados anonimizados utilizando hash.

## Principais pontos

    
**Análises de Vendas e Performance**

    Qual o faturamento total e evolução temporal das vendas?
    Quais os meses/períodos com maior volume de vendas?
    Qual o ticket médio dos pedidos?
    Qual a taxa de crescimento das vendas ao longo do período?
    Qual a distribuição de vendas por categoria de produto?

**Análises de Satisfação**

    Qual a nota média de satisfação dos clientes?
    Quais fatores mais impactam a avaliação (prazo, produto, atendimento)?
    Quais produtos estão mais propensos a avaliações negativas?
    Qual a distribuição das notas (1-5 estrelas)?
    Existe correlação entre atraso na entrega e avaliações negativas?

**Análises de Pagamento**

    Quais as formas de pagamento mais utilizadas?
    Qual o valor médio por tipo de pagamento?
    Existe relação entre método de pagamento e ticket médio?

**Análises de Logística e Entrega**

    Qual o prazo médio de entrega?
    Percentual de entregas no prazo vs atrasadas?

**Análises de Produtos**

    Quais categorias de produtos mais vendidas?
    Produtos com melhores avaliações?

**Análises de Vendedores**

    Quantidade e performance dos vendedores?
    Concentração de vendas (poucos vendem muito)?
    Relação entre localização do vendedor e performance?

**Análises Preditivas e ML**

    Previsão de demanda por categoria/período
    Predição de satisfação do cliente
    Classificação de risco de review negativa
    Previsão de churn de clientes
    Sistemas de recomendação

Entendimento do negócio:

Empresa no ramo de e-commerce atua na modalidade B2B2BC conectando logistas a clientes. Tem como principal característica a centralização dos pedidos, logo, seu público alvo são os vendedores parceiros.

A empresa agrega os pedidos de diferentes plataformas(Mercado Livre, Americanas, Magazine Luiza entre outras) em uma só plataforma, onde cada vendedor tem um painel único, com os pedidos que devem ser embalados e despachados.


Objetivo de Negócio:

Melhorar o desempenho comercial e a satisfação do cliente, orientando decisões baseadas em dados.

Tais perguntas devem ser respondidas:
Como anda as vendas;
Quais estados vendem mais;
Onde está a maior concentração de seus clientes;
Quais fatores mais impactam nas avaliações negativas;
Quais categorias de produtos vendem melhor;
Produtos com maior taxa de avaliações negativas entre outras.


Objetivo de Mineração de Dados:

Realizar uma análise exploratória e preditiva sobre:

 Vendas;
Localização dos clientes;
Categorias de produtos;
Fatores que influenciam as avaliações.


Será considerado um sucesso se as seguintes características forem atendidas:

Aumentar em 5% a captação de novos usuários(Tendo em vista ações de marketing melhor direcionadas)
Melhorar a avaliação média dos pedidos em, no mínimo, 0,2 pontos


Responsáveis e cronograma

A análise será conduzida por Guilherme da Silva Costa, com orientação do Prof Bruno Martins Bartolomeu.

Espera-se que a análise seja concluída até o fim de novembro(29/11/2025). Será utilizado a linguagem python e suas bibliotecas.

## Importação

In [77]:
import pandas as pd

# Origem https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce


costumer = pd.read_csv('olist_customers_dataset.csv')
#local = pd.read_csv('olist_geolocation_dataset.csv')
order_items = pd.read_csv('olist_order_items_dataset.csv')
order_payments = pd.read_csv('olist_order_payments_dataset.csv')
order_reviews = pd.read_csv('olist_order_reviews_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
sellers = pd.read_csv('olist_sellers_dataset.csv')
#category_name_translation = pd.read_csv('product_category_name_translation.csv')

In [78]:
df = orders.merge(order_items, how='left', on='order_id')
df.shape

(113425, 14)

## Data Understending

In [79]:
def visualiza_df(df):
    '''
        Exibe informações básicas do DataFrame que está sendo observado 
    '''
    #Formato do DF
    print('\033[31m Formato:\033[0m')
    print(f'{df.shape[0] :,} linhas e {df.shape[1]} colunas.')
    
    # Valores ausentes
    print(f'{'=' * 50}')
    print('\033[31m Valores ausentes:\033[0m')
    print(df.isnull().sum())

    # Duplicatas
    print(f'{'=' * 50}')
    print('\033[31m Duplicatas: \033[0m')
    print(df.duplicated().sum())

    # Tipos de dados
    print(f'{'=' * 50}')
    print('\033[31m Tipos de dados: \033[0m')
    print(df.dtypes)

    # Visualização dados brutos
    print(f'{'=' * 50}')
    print('\033[31m Pré-visualização dos dados: \033[0m')
    df.head(5)

    return df

In [91]:
visualiza_df(costumer)

 Formato:
99,441 linhas e 4 colunas.
==================================================
 Valores ausentes:
customer_id           0
customer_unique_id    0
customer_city         0
customer_state        0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
customer_id           object
customer_unique_id    object
customer_city         object
customer_state        object
dtype: object
==================================================
 Pré-visualização dos dados:

,customer_id,customer_unique_id,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP
...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,cotia,SP

In [92]:
visualiza_df(sellers)

 Formato:
3,095 linhas e 3 colunas.
==================================================
 Valores ausentes:
seller_id       0
seller_city     0
seller_state    0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
seller_id       object
seller_city     object
seller_state    object
dtype: object
==================================================
 Pré-visualização dos dados:

                             seller_id        seller_city seller_state
0     3442f8959a84dea7ee197c632cb2df15           campinas           SP
1     d1b65fc7debc3361ea86b5f14c68d2e2         mogi guacu           SP
2     ce3ad9de960102d0677a81f5d0bb7b2d     rio de janeiro           RJ
3     c0f3eea2e14555b6faeea3dd58c1b1c3          sao paulo           SP
4     51a04a8a6bdcb23deccc82b0b80742cf  braganca paulista           SP
...                                ...                ...          ...
3090  98dddbc4601dd4443ca174359b237166            sarandi           PR
3091  f8201cab383e484733266d1906e2fdfa            palhoca           SC
3092  74871d19219c7d518d0090283e03c137          sao paulo           SP
3093  e603cf3fec55f8697c9059638d6c8eb5            pelotas           RS
3094  9e25199f6ef7e7c347120ff175652c3b            taubate           SP

[3095 rows x 3 columns]

In [93]:
visualiza_df(orders)

 Formato:
96,478 linhas e 5 colunas.
==================================================
 Valores ausentes:
order_id                         0
customer_id                      0
order_status                     0
order_date                       0
order_estimated_delivery_date    0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
order_id                                 object
customer_id                              object
order_status                             object
order_date                       datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object
==================================================
 Pré-visualização dos dados:

,order_id,customer_id,order_status,order_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-26
...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-04-03

In [94]:
visualiza_df(order_items)

 Formato:
112,650 linhas e 7 colunas.
==================================================
 Valores ausentes:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object
==================================================
 Pré-visualização dos dados:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [95]:
visualiza_df(order_payments)

 Formato:
103,886 linhas e 2 colunas.
==================================================
 Valores ausentes:
order_id        0
payment_type    0
dtype: int64
==================================================
 Duplicatas:
2200
==================================================
 Tipos de dados:
order_id        object
payment_type    object
dtype: object
==================================================
 Pré-visualização dos dados:

                                order_id payment_type
0       b81ef226f3fe1789b1e8b2acac839d17  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd  credit_card
3       ba78997921bbcdc1373bb41e913ab953  credit_card
4       42fdf880ba16b47b59251dd489d4441a  credit_card
...                                  ...          ...
103881  0406037ad97740d563a178ecc7a2075c       boleto
103882  7b905861d7c825891d6347454ea7863f  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf  credit_card
103884  b8b61059626efa996a60be9bb9320e10  credit_card
103885  28bbae6599b09d39ca406b747b6632b1       boleto

[103886 rows x 2 columns]

In [96]:
visualiza_df(order_reviews)

 Formato:
99,224 linhas e 3 colunas.
==================================================
 Valores ausentes:
review_id       0
order_id        0
review_score    0
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
review_id       object
order_id        object
review_score     int64
dtype: object
==================================================
 Pré-visualização dos dados:

,review_id,order_id,review_score
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5
...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1

In [97]:
visualiza_df(products)

 Formato:
32,951 linhas e 2 colunas.
==================================================
 Valores ausentes:
product_id                 0
product_category_name    610
dtype: int64
==================================================
 Duplicatas:
0
==================================================
 Tipos de dados:
product_id               object
product_category_name    object
dtype: object
==================================================
 Pré-visualização dos dados:

                             product_id              product_category_name
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

[32951 rows x 2 columns]

In [98]:
produtos_sem_categoria = order_items.merge(products, how='left', on='product_id')
produtos_sem_categoria.isnull().sum()

order_id                    0
order_item_id               0
product_id                  0
seller_id                   0
shipping_limit_date         0
price                       0
freight_value               0
product_category_name    1603
dtype: int64

## Data Preparation

### Alteração tipo de dados

In [88]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

### Limpeza das colunas

In [89]:
products = products.drop(columns={'product_description_lenght', 'product_photos_qty', 'product_name_lenght', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm'}, axis=1)
order_reviews = order_reviews.drop(columns={'review_comment_title', 'review_comment_message', 'review_answer_timestamp', 'review_creation_date'}, axis=1)
orders = orders.drop(columns={'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date'}, axis=1)
orders= orders[orders['order_status'] == 'delivered']
order_payments = order_payments.drop(columns={'payment_sequential', 'payment_installments', 'payment_value'}, axis=1)
costumer = costumer.drop(columns={'customer_zip_code_prefix'}, axis=1)
sellers = sellers.drop(columns={'seller_zip_code_prefix'}, axis=1)

### Renomear Colunas

In [90]:
orders = orders.rename(columns={'order_purchase_timestamp': 'order_date'})